# Configuration file

endless:
  projectName: demostore
  prefix: ${opt:stage, self:provider.stage}-${self:custom.endless.projectName}

s3:
  localDir: frontend
  bucketName: dev-demostore-frontend
  acl: public-read
  index: index.html
  
dynamodb:
  prefix: dev-demostore