# Resources file

FrontendBucket:
  Type: AWS::S3::Bucket
  Properties:
     BucketName: ${self:custom.prefix}-frontend
MediaBucket:
  Type: AWS::S3::Bucket
  Properties:
     BucketName: ${self:custom.prefix}-media
ProductTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.prefix}-product
    AttributeDefinitions:
      - AttributeName: sku
        AttributeType: S
    KeySchema:
      - AttributeName: sku
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
CustomerTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.prefix}-customer
    AttributeDefinitions:
      - AttributeName: customerId
        AttributeType: S
    KeySchema:
      - AttributeName: customerId
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
CartTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.prefix}-cart
    AttributeDefinitions:
      - AttributeName: cartId
        AttributeType: S
    KeySchema:
      - AttributeName: cartId
        KeyType: HASH
    ProvisionedThroughput:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5
DynamoDBIamPolicy:
  Type: AWS::IAM::Policy
  DependsOn: 
    - ProductTable
    - CustomerTable
    - CartTable
  Properties:
    PolicyName: lambda-dynamodb
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource:
            - arn:aws:dynamodb:*:*:table/${self:custom.prefix}-product
            - arn:aws:dynamodb:*:*:table/${self:custom.prefix}-customer
            - arn:aws:dynamodb:*:*:table/${self:custom.prefix}-cart
    Roles:
      - Ref: IamRoleLambdaExecution